/**
 * Summary Types
 *
 * TypeScript interfaces for newsletter summary entities.
 * These types mirror the backend Python models in src/models/summary.py
 *
 * Summaries are generated by LLM processing of raw newsletter content
 * and contain structured extractions of key information.
 *
 * @see Backend model: src/models/summary.py
 */

/**
 * Newsletter Summary entity
 *
 * Contains structured information extracted from a newsletter by the LLM.
 * Each newsletter has at most one summary (1:1 relationship).
 */
export interface NewsletterSummary {
  /** Unique identifier (UUID) */
  id: string

  /** ID of the newsletter this summary belongs to */
  newsletterId: string

  /**
   * Executive summary - 2-3 sentence high-level overview
   * Suitable for leadership or quick scanning
   */
  executiveSummary: string

  /**
   * Key themes identified in the newsletter
   * Array of theme names/topics covered
   */
  keyThemes: string[]

  /**
   * Strategic insights for business leaders
   * Higher-level implications and recommendations
   */
  strategicInsights: string[]

  /**
   * Technical details for practitioners
   * Implementation notes, code references, technical depth
   */
  technicalDetails: string[]

  /**
   * Actionable items extracted from the content
   * Things readers could implement or investigate
   */
  actionableItems: string[]

  /**
   * Notable quotes from the newsletter
   * Interesting or impactful statements
   */
  notableQuotes: string[]

  /**
   * Relevant links for further reading
   * URLs mentioned in the newsletter worth highlighting
   */
  relevantLinks: string[]

  /**
   * Agent framework used for summarization
   * e.g., "claude-sdk", "langchain", "autogen"
   */
  agentFramework: string

  /**
   * LLM model identifier used
   * e.g., "claude-haiku-4-5", "gpt-4o"
   */
  modelUsed: string

  /**
   * Specific model version (if available)
   */
  modelVersion: string | null

  /** When the summary was created */
  createdAt: string // ISO 8601 date string

  /** Total tokens used in generation */
  tokenUsage: number

  /** Time taken to generate in seconds */
  processingTimeSeconds: number
}

/**
 * Summary list item (lightweight view)
 *
 * For displaying in lists without full content
 */
export interface SummaryListItem {
  id: string
  newsletterId: string
  /** Newsletter title for display */
  newsletterTitle?: string
  /** Newsletter publication name */
  newsletterPublication?: string | null
  /** First 200 chars of executive summary */
  executiveSummaryPreview: string
  keyThemes: string[]
  modelUsed: string
  createdAt: string
  processingTimeSeconds: number
}

/**
 * Request to trigger summarization
 */
export interface SummarizeRequest {
  /** Newsletter IDs to summarize (if empty, summarizes all pending) */
  newsletterIds?: string[]
  /** Force re-summarization even if summary exists */
  force?: boolean
  /** Model to use for summarization (uses default if not specified) */
  model?: string
}

/**
 * Response from summarization trigger
 */
export interface SummarizeResponse {
  /** Task ID for tracking progress */
  taskId: string
  /** Number of newsletters queued for summarization */
  queuedCount: number
  /** IDs of newsletters being processed */
  newsletterIds: string[]
}

/**
 * Progress event for summarization task (SSE)
 */
export interface SummarizationProgress {
  /** Task identifier */
  taskId: string
  /** Current step description */
  step: string
  /** Progress percentage (0-100) */
  progress: number
  /** Currently processing newsletter ID */
  currentNewsletterId?: string
  /** Count of completed summaries */
  completedCount: number
  /** Total count to process */
  totalCount: number
  /** Status: processing, completed, or error */
  status: "processing" | "completed" | "error"
  /** Error message if status is error */
  errorMessage?: string
}

/**
 * Filters for summary list queries
 */
export interface SummaryFilters {
  /** Filter by newsletter ID */
  newsletterId?: string
  /** Filter by model used */
  modelUsed?: string
  /** Filter after this date */
  startDate?: string
  /** Filter before this date */
  endDate?: string
  /** Pagination limit */
  limit?: number
  /** Pagination offset */
  offset?: number
}
