/**
 * Summary Types
 *
 * TypeScript interfaces for newsletter summary entities.
 * These types mirror the backend Python models in src/models/summary.py
 *
 * Summaries are generated by LLM processing of raw newsletter content
 * and contain structured extractions of key information.
 *
 * @see Backend model: src/models/summary.py
 */

/**
 * Newsletter Summary entity
 *
 * Contains structured information extracted from a newsletter or content by the LLM.
 * Supports both legacy Newsletter model and new unified Content model.
 *
 * Note: Field names use snake_case to match the Python backend API responses.
 */
export interface NewsletterSummary {
  /** Unique identifier */
  id: number

  /** ID of the newsletter this summary belongs to (null for content-only) */
  newsletter_id: number | null

  /** ID of the content this summary belongs to (null for newsletter-only) */
  content_id?: number | null

  /**
   * Executive summary - 2-3 sentence high-level overview
   * Suitable for leadership or quick scanning
   */
  executive_summary: string

  /**
   * Key themes identified in the newsletter
   * Array of theme names/topics covered
   */
  key_themes: string[]

  /**
   * Strategic insights for business leaders
   * Higher-level implications and recommendations
   */
  strategic_insights: string[]

  /**
   * Technical details for practitioners
   * Implementation notes, code references, technical depth
   */
  technical_details: string[]

  /**
   * Actionable items extracted from the content
   * Things readers could implement or investigate
   */
  actionable_items: string[]

  /**
   * Notable quotes from the newsletter
   * Interesting or impactful statements
   */
  notable_quotes: string[]

  /**
   * Relevant links for further reading
   * URLs mentioned in the newsletter worth highlighting
   */
  relevant_links: Array<Record<string, unknown>>

  /**
   * Relevance scores for different audience segments
   */
  relevance_scores: {
    cto_leadership: number
    technical_teams: number
    individual_developers: number
  }

  /**
   * Agent framework used for summarization
   * e.g., "claude-sdk", "langchain", "autogen"
   */
  agent_framework: string

  /**
   * LLM model identifier used
   * e.g., "claude-haiku-4-5", "gpt-4o"
   */
  model_used: string

  /**
   * Specific model version (if available)
   */
  model_version: string | null

  /** When the summary was created */
  created_at: string // ISO 8601 date string

  /** Total tokens used in generation */
  token_usage: number | null

  /** Time taken to generate in seconds */
  processing_time_seconds: number | null
}

/**
 * Summary list item (lightweight view)
 *
 * For displaying in lists without full content.
 * Supports both newsletter-based and content-based summaries.
 */
export interface SummaryListItem {
  id: number
  /** Newsletter ID (null for content-only summaries) */
  newsletter_id: number | null
  /** Content ID for unified Content model */
  content_id?: number | null
  /** Newsletter/Content title for display */
  newsletter_title?: string
  /** Newsletter publication name */
  newsletter_publication?: string | null
  /** First 200 chars of executive summary */
  executive_summary_preview: string
  key_themes: string[]
  model_used: string
  created_at: string
  processing_time_seconds: number | null
}

/**
 * Request to trigger summarization
 */
export interface SummarizeRequest {
  /** Newsletter IDs to summarize (if empty, summarizes all pending) */
  newsletter_ids?: number[]
  /** Force re-summarization even if summary exists */
  force?: boolean
  /** Model to use for summarization (uses default if not specified) */
  model?: string
}

/**
 * Response from summarization trigger
 */
export interface SummarizeResponse {
  /** Task ID for tracking progress */
  task_id: string
  /** Message from the server */
  message: string
  /** Number of newsletters queued for summarization */
  queued_count: number
  /** IDs of newsletters being processed */
  newsletter_ids: number[]
}

/**
 * Progress event for summarization task (SSE)
 */
export interface SummarizationProgress {
  /** Task identifier */
  task_id: string
  /** Current step description */
  step?: string
  /** Progress percentage (0-100) */
  progress: number
  /** Currently processing newsletter ID */
  current_newsletter_id?: number
  /** Count of completed summaries */
  completed_count?: number
  /** Total count to process */
  total_count?: number
  /** Count of processed */
  processed?: number
  /** Total */
  total?: number
  /** Status: processing, completed, or error */
  status: "queued" | "processing" | "completed" | "error"
  /** Message from the server */
  message?: string
}

/**
 * Filters for summary list queries
 */
export interface SummaryFilters {
  /** Filter by newsletter ID */
  newsletter_id?: number
  /** Filter by model used */
  model_used?: string
  /** Filter after this date */
  start_date?: string
  /** Filter before this date */
  end_date?: string
  /** Pagination limit */
  limit?: number
  /** Pagination offset */
  offset?: number
}
