"""``api.contracts`` producer over the machine-readable contract schemas.

The canonical owner of API/binding contracts is the stable schema tree under
``openspec/contracts/`` (JSON Schema, OpenAPI). This producer:

* validates every ``openspec/contracts/**/*.schema.json`` parses and is a valid
  Draft 2020-12 schema (the binding-validation surface); and
* renders a deterministic inventory of those contracts into a generated marker
  block, so a newly added or removed contract shows as precise drift.

A schema that does not parse or is not a valid schema makes the producer
``failed`` with a bounded error — a broken contract cannot be trustworthily
indexed. The producer never writes into ``openspec/contracts/`` (it only reads
it); its single managed output is the inventory file.
"""

from __future__ import annotations

import json
from pathlib import Path

from jsonschema import Draft202012Validator
from jsonschema.exceptions import SchemaError

import results as R
from _runtime import Remediation, SafeError
from inventory_file import apply_block
from registry import API_CONTRACTS, Mode, Producer, ProducerSpec

PRODUCER_ID = API_CONTRACTS
PRODUCER_VERSION = "1.0.0"
OWNER = "openspec/contracts/ (machine-readable contract schemas)"

_CONTRACTS_ROOT = "openspec/contracts"
_INVENTORY_TARGET = "docs/architecture-analysis/contracts-inventory.md"
_BLOCK_ID = "contracts-inventory"
_REGEN_COMMAND = "make context-refresh"


def _schema_files(repository: Path) -> list[Path]:
    root = repository / _CONTRACTS_ROOT
    if not root.is_dir():
        return []
    return sorted(root.rglob("*.schema.json"))


def _capability(repository: Path, schema: Path) -> str:
    rel = schema.relative_to(repository / _CONTRACTS_ROOT)
    return rel.parts[0] if len(rel.parts) > 1 else "(root)"


def render_contracts_inventory(repository: Path, entries: list[tuple[str, str, str]]) -> str:
    """Render the deterministic contracts table body from validated *entries*."""
    lines = [
        f"_{len(entries)} contract schema(s). Generated by {PRODUCER_ID}@{PRODUCER_VERSION}._",
        "",
        "| Capability | Schema | `$id` |",
        "| --- | --- | --- |",
    ]
    for capability, rel, schema_id in entries:
        lines.append(f"| `{capability}` | `{rel}` | `{schema_id}` |")
    return "\n".join(lines)


class ApiContractsProducer(Producer):
    """Validate contract schemas and render their deterministic inventory."""

    def __init__(self) -> None:
        self.spec = ProducerSpec(
            producer_id=PRODUCER_ID,
            producer_version=PRODUCER_VERSION,
            owner=OWNER,
            inputs=(f"{_CONTRACTS_ROOT}/**/*.schema.json",),
            outputs=(_INVENTORY_TARGET,),
        )

    def run(self, mode: Mode, repository: Path, source_revision: str):
        validations: list = []
        entries: list[tuple[str, str, str]] = []
        for schema in _schema_files(repository):
            rel = schema.relative_to(repository).as_posix()
            try:
                data = json.loads(schema.read_text(encoding="utf-8"))
            except json.JSONDecodeError as exc:
                return self._failed(f"{rel}: invalid JSON ({exc.msg})")
            try:
                Draft202012Validator.check_schema(data)
            except SchemaError as exc:
                return self._failed(f"{rel}: invalid JSON Schema ({exc.message})")
            schema_id = data.get("$id", "(no $id)")
            entries.append((_capability(repository, schema), rel, schema_id))
            validations.append(R.passed(R.vid("schema", rel), "valid Draft 2020-12 schema"))

        body = render_contracts_inventory(repository, entries)
        outcome = apply_block(
            repository,
            target_rel=_INVENTORY_TARGET,
            block_id=_BLOCK_ID,
            title="Contracts inventory",
            body=body,
            mode=mode,
        )
        if outcome.marker_error is not None:
            return R.failed(
                PRODUCER_ID,
                PRODUCER_VERSION,
                error=outcome.marker_error,
                remediation=[
                    Remediation(
                        summary=f"Repair the generated markers in {_INVENTORY_TARGET}.",
                    )
                ],
                validations=[outcome.validation],
            )
        validations.append(outcome.validation)
        artifacts = (outcome.artifact,) if outcome.artifact is not None else ()

        if mode == "check" and outcome.drifted:
            return R.drift(
                PRODUCER_ID,
                PRODUCER_VERSION,
                artifacts=artifacts,
                validations=validations,
                remediation=[
                    Remediation(
                        summary="Regenerate the contracts inventory.",
                        command=_REGEN_COMMAND,
                    )
                ],
            )
        if mode == "generate" and artifacts:
            return R.generated(
                PRODUCER_ID, PRODUCER_VERSION, artifacts=artifacts, validations=validations
            )
        return R.fresh(PRODUCER_ID, PRODUCER_VERSION, validations=validations)

    def _failed(self, summary: str):
        return R.failed(
            PRODUCER_ID,
            PRODUCER_VERSION,
            error=SafeError("ContractSchemaError", summary),
            remediation=[
                Remediation(summary="Fix the malformed contract schema and re-run.")
            ],
            validations=[R.failed_validation("api.contracts", summary)],
        )
