"""``decisions.timeline`` producer over the canonical decision-index owner.

The decision index (``docs/decisions/<capability>.md``) is generated by
``skills/explore-feature/scripts/archive_index.py`` (the ``make decisions``
target). This adapter reuses that exact entry point — it never re-implements
decision parsing — and adds the shared generate/check protocol:

* ``generate`` renders the full index into a tempdir and syncs changed files
  onto ``docs/decisions/`` (identical outcome to ``make decisions``);
* ``check`` renders into a tempdir and byte-compares, writing nothing.

Determinism comes from the owner: decisions are sorted by content-derived phase
date and change id, never by wall-clock time.
"""

from __future__ import annotations

import sys
import tempfile
from pathlib import Path

import results as R
from _runtime import Remediation, SafeError
from registry import DECISIONS_TIMELINE, Mode, Producer, ProducerSpec
from tree_diff import diff_trees, sync_tree

# The decision-index owner lives in the explore-feature skill.
_OWNER_SCRIPTS = Path(__file__).resolve().parents[2] / "explore-feature" / "scripts"
if _OWNER_SCRIPTS.is_dir() and str(_OWNER_SCRIPTS) not in sys.path:
    sys.path.insert(0, str(_OWNER_SCRIPTS))

PRODUCER_ID = DECISIONS_TIMELINE
#: Bump only if this adapter changes; the owner's format is versioned upstream.
PRODUCER_VERSION = "1.0.0"
OWNER = "skills/explore-feature/scripts/archive_index.py (make decisions)"

_DECISIONS_DIR = "docs/decisions"
_ARCHIVE_ROOT = "openspec/changes"
_CAPABILITIES_ROOT = "openspec/specs"
_REGEN_COMMAND = "make decisions"


def _render_index(repository: Path, output_dir: Path) -> None:
    """Render the full decision index into *output_dir* via the canonical owner."""
    from archive_index import emit_decisions_from_archive

    emit_decisions_from_archive(
        archive_root=repository / _ARCHIVE_ROOT,
        output_dir=output_dir,
        capabilities_root=repository / _CAPABILITIES_ROOT,
        strict=False,
    )


class DecisionsTimelineProducer(Producer):
    """Adapter around the decision-index owner using the tempdir-diff protocol."""

    def __init__(self) -> None:
        self.spec = ProducerSpec(
            producer_id=PRODUCER_ID,
            producer_version=PRODUCER_VERSION,
            owner=OWNER,
            inputs=(f"{_ARCHIVE_ROOT}/**/session-log.md", f"{_CAPABILITIES_ROOT}/*"),
            outputs=(f"{_DECISIONS_DIR}/",),
        )

    def run(self, mode: Mode, repository: Path, source_revision: str):
        committed = repository / _DECISIONS_DIR
        try:
            with tempfile.TemporaryDirectory(prefix="ctx-decisions-") as tmp:
                rendered_root = Path(tmp)
                _render_index(repository, rendered_root)
                artifacts = diff_trees(
                    committed, rendered_root, path_prefix=_DECISIONS_DIR, patterns=("*.md",)
                )
                if mode == "generate":
                    if artifacts:
                        committed.mkdir(parents=True, exist_ok=True)
                        sync_tree(committed, rendered_root, artifacts, path_prefix=_DECISIONS_DIR)
                        return R.generated(
                            PRODUCER_ID,
                            PRODUCER_VERSION,
                            artifacts=artifacts,
                            validations=[R.passed("decisions", f"regenerated {len(artifacts)} file(s)")],
                        )
                    return R.fresh(
                        PRODUCER_ID,
                        PRODUCER_VERSION,
                        validations=[R.passed("decisions", f"{_DECISIONS_DIR} is current")],
                    )
                # check mode
                if artifacts:
                    return R.drift(
                        PRODUCER_ID,
                        PRODUCER_VERSION,
                        artifacts=artifacts,
                        validations=[R.failed_validation("decisions", f"{_DECISIONS_DIR} is stale")],
                        remediation=[
                            Remediation(
                                summary="Regenerate the decision index.",
                                command=_REGEN_COMMAND,
                            )
                        ],
                    )
                return R.fresh(
                    PRODUCER_ID,
                    PRODUCER_VERSION,
                    validations=[R.passed("decisions", f"{_DECISIONS_DIR} is current")],
                )
        except Exception as exc:  # noqa: BLE001 - surfaced as a failed result
            return R.failed(
                PRODUCER_ID,
                PRODUCER_VERSION,
                error=SafeError(exc.__class__.__name__, str(exc)[:300]),
                remediation=[
                    Remediation(
                        summary="Inspect the decision-index owner and re-run.",
                        command=_REGEN_COMMAND,
                    )
                ],
                validations=[R.failed_validation("decisions", "render failed")],
            )
