"""Tests for digest markdown generation utilities."""

import pytest

from src.utils.digest_markdown import (
    enrich_digest_data,
    extract_digest_theme_tags,
    extract_source_content_ids,
    generate_digest_markdown,
    parse_markdown_digest,
)


@pytest.fixture
def sample_digest_data():
    """Sample digest data for testing."""
    return {
        "title": "Weekly AI Digest - January 2025",
        "executive_overview": "This week saw major advances in AI agents and multimodal models.",
        "strategic_insights": [
            {
                "title": "AI Agent Frameworks Mature",
                "summary": "Enterprise adoption of AI agents accelerated significantly.",
                "details": [
                    "LangChain and LlamaIndex see 50% growth",
                    "Production deployments up 3x from last quarter",
                ],
                "themes": ["AI Agents", "Enterprise AI"],
                "continuity": "Continues trend from Q3 agent framework expansion",
            },
            {
                "title": "Cost Optimization Focus",
                "summary": "Organizations prioritizing AI cost management.",
                "details": ["Token optimization techniques gaining traction"],
                "themes": ["Cost Management"],
            },
        ],
        "technical_developments": [
            {
                "title": "Claude 3.5 Performance Improvements",
                "summary": "New benchmarks show significant gains.",
                "details": ["30% faster inference", "Improved tool use"],
                "themes": ["LLMs", "Performance"],
            }
        ],
        "emerging_trends": [
            {
                "title": "Agentic RAG",
                "summary": "Combining agents with retrieval for better results.",
                "details": ["Self-correcting retrieval patterns"],
                "themes": ["RAG", "AI Agents"],
            }
        ],
        "actionable_recommendations": {
            "ctos": ["Evaluate agent frameworks for 2025 roadmap"],
            "developers": ["Start experimenting with tool-use patterns"],
        },
        "sources": [
            {
                "title": "AI Weekly Newsletter",
                "publication": "AI Weekly",
                "url": "https://example.com/ai-weekly",
                "content_id": 101,
            },
            {
                "title": "Tech Trends Report",
                "publication": "Tech Trends",
                "newsletter_id": 102,  # Legacy field
            },
        ],
        "historical_context": [
            {
                "title": "AI Agent Evolution",
                "content": "Agent frameworks have evolved significantly since 2023.",
            }
        ],
    }


class TestGenerateDigestMarkdown:
    """Tests for generate_digest_markdown function."""

    def test_generates_title(self, sample_digest_data):
        """Title is generated as H1."""
        md = generate_digest_markdown(sample_digest_data)
        assert "# Weekly AI Digest - January 2025" in md

    def test_generates_executive_overview(self, sample_digest_data):
        """Executive overview section is generated."""
        md = generate_digest_markdown(sample_digest_data)
        assert "## Executive Overview" in md
        assert "major advances in AI agents" in md

    def test_generates_strategic_insights(self, sample_digest_data):
        """Strategic insights section is generated with audience tag."""
        md = generate_digest_markdown(sample_digest_data)
        assert "## Strategic Insights" in md
        assert "*For CTOs and Technical Leaders*" in md
        assert "### AI Agent Frameworks Mature" in md

    def test_generates_technical_developments(self, sample_digest_data):
        """Technical developments section is generated."""
        md = generate_digest_markdown(sample_digest_data)
        assert "## Technical Developments" in md
        assert "*For Developers and Practitioners*" in md
        assert "### Claude 3.5 Performance Improvements" in md

    def test_generates_emerging_trends(self, sample_digest_data):
        """Emerging trends section is generated."""
        md = generate_digest_markdown(sample_digest_data)
        assert "## Emerging Trends" in md
        assert "### Agentic RAG" in md

    def test_generates_actionable_recommendations(self, sample_digest_data):
        """Actionable recommendations section is generated by role."""
        md = generate_digest_markdown(sample_digest_data)
        assert "## Actionable Recommendations" in md
        assert "### Ctos" in md
        assert "### Developers" in md
        assert "- Evaluate agent frameworks" in md

    def test_generates_sources_section(self, sample_digest_data):
        """Sources section is generated with links."""
        md = generate_digest_markdown(sample_digest_data)
        assert "## Sources" in md
        assert "[AI Weekly Newsletter](https://example.com/ai-weekly)" in md
        assert "Tech Trends Report (Tech Trends)" in md  # No URL

    def test_generates_historical_context(self, sample_digest_data):
        """Historical context section is generated."""
        md = generate_digest_markdown(sample_digest_data)
        assert "## Historical Context" in md
        assert "### AI Agent Evolution" in md

    def test_includes_theme_hashtags(self, sample_digest_data):
        """Theme hashtags are included in section output."""
        md = generate_digest_markdown(sample_digest_data)
        assert "#AI-Agents" in md or "#AI_Agents" in md or "AI Agents" in md

    def test_includes_historical_continuity(self, sample_digest_data):
        """Historical continuity is included as blockquote."""
        md = generate_digest_markdown(sample_digest_data)
        assert "Continues trend from Q3" in md

    def test_handles_empty_data(self):
        """Empty data returns empty string."""
        md = generate_digest_markdown({})
        assert md == ""

    def test_handles_partial_data(self):
        """Partial data only generates present sections."""
        partial_data = {
            "title": "Quick Digest",
            "executive_overview": "Brief overview.",
        }
        md = generate_digest_markdown(partial_data)
        assert "# Quick Digest" in md
        assert "## Executive Overview" in md
        assert "## Strategic Insights" not in md


class TestExtractDigestThemeTags:
    """Tests for extract_digest_theme_tags function."""

    def test_extracts_from_strategic_insights(self, sample_digest_data):
        """Extracts themes from strategic insights."""
        themes = extract_digest_theme_tags(sample_digest_data)
        assert "AI Agents" in themes
        assert "Enterprise AI" in themes

    def test_extracts_from_technical_developments(self, sample_digest_data):
        """Extracts themes from technical developments."""
        themes = extract_digest_theme_tags(sample_digest_data)
        assert "LLMs" in themes
        assert "Performance" in themes

    def test_extracts_from_emerging_trends(self, sample_digest_data):
        """Extracts themes from emerging trends."""
        themes = extract_digest_theme_tags(sample_digest_data)
        assert "RAG" in themes

    def test_deduplicates_themes(self, sample_digest_data):
        """Duplicate themes are removed."""
        themes = extract_digest_theme_tags(sample_digest_data)
        # "AI Agents" appears in both strategic_insights and emerging_trends
        ai_agents_count = sum(1 for t in themes if t == "AI Agents")
        assert ai_agents_count == 1

    def test_empty_sections(self):
        """Empty sections return empty list."""
        themes = extract_digest_theme_tags({})
        assert themes == []


class TestExtractSourceContentIds:
    """Tests for extract_source_content_ids function."""

    def test_extracts_content_ids(self, sample_digest_data):
        """Extracts content_id from sources."""
        ids = extract_source_content_ids(sample_digest_data)
        assert 101 in ids

    def test_extracts_newsletter_ids_as_fallback(self, sample_digest_data):
        """Extracts newsletter_id when content_id not present."""
        ids = extract_source_content_ids(sample_digest_data)
        assert 102 in ids

    def test_deduplicates_ids(self):
        """Duplicate IDs are removed."""
        data = {
            "sources": [
                {"content_id": 1},
                {"content_id": 1},
                {"content_id": 2},
            ]
        }
        ids = extract_source_content_ids(data)
        assert len(ids) == 2
        assert 1 in ids
        assert 2 in ids

    def test_empty_sources(self):
        """Empty sources returns empty list."""
        ids = extract_source_content_ids({"sources": []})
        assert ids == []

    def test_no_sources_field(self):
        """Missing sources field returns empty list."""
        ids = extract_source_content_ids({})
        assert ids == []


class TestEnrichDigestData:
    """Tests for enrich_digest_data function."""

    def test_adds_markdown_content(self, sample_digest_data):
        """Enrichment adds markdown_content field."""
        enriched = enrich_digest_data(sample_digest_data)
        assert "markdown_content" in enriched
        assert "## Executive Overview" in enriched["markdown_content"]

    def test_adds_theme_tags(self, sample_digest_data):
        """Enrichment adds theme_tags field."""
        enriched = enrich_digest_data(sample_digest_data)
        assert "theme_tags" in enriched
        assert "AI Agents" in enriched["theme_tags"]

    def test_adds_source_content_ids(self, sample_digest_data):
        """Enrichment adds source_content_ids field."""
        enriched = enrich_digest_data(sample_digest_data)
        assert "source_content_ids" in enriched
        assert 101 in enriched["source_content_ids"]

    def test_preserves_existing_fields(self, sample_digest_data):
        """Enrichment preserves all existing fields."""
        enriched = enrich_digest_data(sample_digest_data)
        assert enriched["title"] == sample_digest_data["title"]
        assert enriched["executive_overview"] == sample_digest_data["executive_overview"]

    def test_does_not_overwrite_existing_markdown(self):
        """Existing markdown_content is not overwritten."""
        data = {
            "title": "Test",
            "markdown_content": "# Custom",
        }
        enriched = enrich_digest_data(data)
        assert enriched["markdown_content"] == "# Custom"


class TestParseMarkdownDigest:
    """Tests for parse_markdown_digest function."""

    def test_parses_title(self, sample_digest_data):
        """Parses title from markdown."""
        md = generate_digest_markdown(sample_digest_data)
        parsed = parse_markdown_digest(md)
        assert "title" in parsed
        assert "Weekly AI Digest" in parsed["title"]

    def test_parses_executive_overview(self, sample_digest_data):
        """Parses executive overview from markdown."""
        md = generate_digest_markdown(sample_digest_data)
        parsed = parse_markdown_digest(md)
        assert "executive_overview" in parsed
        assert "major advances" in parsed["executive_overview"]

    def test_parses_strategic_insights(self, sample_digest_data):
        """Parses strategic insights from markdown."""
        md = generate_digest_markdown(sample_digest_data)
        parsed = parse_markdown_digest(md)
        assert "strategic_insights" in parsed
        # May not get all details due to parsing complexity

    def test_parses_actionable_recommendations(self, sample_digest_data):
        """Parses actionable recommendations from markdown."""
        md = generate_digest_markdown(sample_digest_data)
        parsed = parse_markdown_digest(md)
        assert "actionable_recommendations" in parsed

    def test_parses_sources(self, sample_digest_data):
        """Parses sources from markdown."""
        md = generate_digest_markdown(sample_digest_data)
        parsed = parse_markdown_digest(md)
        assert "sources" in parsed
        assert len(parsed["sources"]) >= 1


class TestDigestSectionFormatting:
    """Tests for digest section formatting."""

    def test_section_with_all_fields(self):
        """Section with all fields is formatted correctly."""
        data = {
            "strategic_insights": [
                {
                    "title": "Test Insight",
                    "summary": "Summary text.",
                    "details": ["Detail 1", "Detail 2"],
                    "themes": ["Theme A", "Theme B"],
                    "continuity": "Historical note here.",
                }
            ]
        }
        md = generate_digest_markdown(data)
        assert "### Test Insight" in md
        assert "Summary text." in md
        assert "- Detail 1" in md
        assert "Theme" in md  # Themes appear somewhere
        assert "Historical note" in md

    def test_section_with_minimal_fields(self):
        """Section with minimal fields is formatted."""
        data = {
            "strategic_insights": [
                {
                    "title": "Simple Insight",
                    "summary": "Just a summary.",
                }
            ]
        }
        md = generate_digest_markdown(data)
        assert "### Simple Insight" in md
        assert "Just a summary." in md

    def test_string_sections(self):
        """String sections (not dicts) are formatted as list items."""
        data = {"emerging_trends": ["Trend 1", "Trend 2"]}
        md = generate_digest_markdown(data)
        assert "- Trend 1" in md or "Trend 1" in md

    def test_section_with_followup_prompts(self):
        """Section with follow-up prompts includes details block."""
        data = {
            "strategic_insights": [
                {
                    "title": "Test Insight",
                    "summary": "Summary text.",
                    "details": ["Detail 1"],
                    "themes": ["Theme A"],
                    "followup_prompts": [
                        "Analyze the impact of X on enterprise AI adoption.",
                        "Compare X and Y for production deployments.",
                    ],
                }
            ]
        }
        md = generate_digest_markdown(data)
        assert "<details>" in md
        assert "Follow-up prompts (2)" in md
        assert "**1.** Analyze the impact of X" in md
        assert "**2.** Compare X and Y" in md
        assert "</details>" in md

    def test_section_without_followup_prompts(self):
        """Section without follow-up prompts has no details block."""
        data = {
            "strategic_insights": [
                {
                    "title": "Test Insight",
                    "summary": "Summary text.",
                }
            ]
        }
        md = generate_digest_markdown(data)
        assert "<details>" not in md
        assert "Follow-up prompts" not in md

    def test_section_with_empty_followup_prompts(self):
        """Section with empty follow-up prompts list has no details block."""
        data = {
            "strategic_insights": [
                {
                    "title": "Test Insight",
                    "summary": "Summary text.",
                    "followup_prompts": [],
                }
            ]
        }
        md = generate_digest_markdown(data)
        assert "<details>" not in md


class TestDigestSectionBackwardCompatibility:
    """Tests for DigestSection backward compatibility with followup_prompts."""

    def test_digest_section_without_followup_prompts(self):
        """DigestSection from dict without followup_prompts defaults to empty list."""
        from src.models.digest import DigestSection

        section = DigestSection(
            title="Test",
            summary="Summary",
            details=["Detail 1"],
            themes=["Theme"],
        )
        assert section.followup_prompts == []

    def test_digest_section_from_dict_without_followup_prompts(self):
        """DigestSection deserialized from dict without followup_prompts yields empty list."""
        from src.models.digest import DigestSection

        data = {
            "title": "Test",
            "summary": "Summary",
            "details": ["Detail 1"],
            "themes": ["Theme"],
            "continuity": None,
        }
        section = DigestSection.model_validate(data)
        assert section.followup_prompts == []

    def test_digest_section_with_followup_prompts(self):
        """DigestSection with followup_prompts preserves them."""
        from src.models.digest import DigestSection

        data = {
            "title": "Test",
            "summary": "Summary",
            "followup_prompts": ["Prompt 1", "Prompt 2"],
        }
        section = DigestSection.model_validate(data)
        assert section.followup_prompts == ["Prompt 1", "Prompt 2"]

    def test_digest_request_max_followup_prompts_default(self):
        """DigestRequest defaults max_followup_prompts to 3."""
        from datetime import datetime

        from src.models.digest import DigestRequest, DigestType

        request = DigestRequest(
            digest_type=DigestType.DAILY,
            period_start=datetime(2025, 1, 1),
            period_end=datetime(2025, 1, 2),
        )
        assert request.max_followup_prompts == 3
