"""add_relevant_links_to_newsletter_summaries

Revision ID: 2969e6a07e38
Revises: cac03dbe5653
Create Date: 2025-12-30 22:43:18.896187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2969e6a07e38'
down_revision: Union[str, None] = 'cac03dbe5653'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add relevant_links column with empty array as default for existing rows
    op.add_column('newsletter_summaries', sa.Column('relevant_links', sa.JSON(), nullable=False, server_default='[]'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove relevant_links column
    op.drop_column('newsletter_summaries', 'relevant_links')
    # ### end Alembic commands ###
