"""initial schema

Revision ID: 95c3f972ad83
Revises: 
Create Date: 2025-12-26 16:29:32.455940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95c3f972ad83'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('digests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('digest_type', sa.Enum('DAILY', 'WEEKLY', name='digesttype'), nullable=False),
    sa.Column('period_start', sa.DateTime(), nullable=False),
    sa.Column('period_end', sa.DateTime(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('executive_overview', sa.Text(), nullable=False),
    sa.Column('strategic_insights', sa.JSON(), nullable=False),
    sa.Column('technical_developments', sa.JSON(), nullable=False),
    sa.Column('emerging_trends', sa.JSON(), nullable=False),
    sa.Column('actionable_recommendations', sa.JSON(), nullable=False),
    sa.Column('sources', sa.JSON(), nullable=False),
    sa.Column('historical_context', sa.JSON(), nullable=True),
    sa.Column('newsletter_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'GENERATING', 'COMPLETED', 'FAILED', 'DELIVERED', name='digeststatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('agent_framework', sa.String(length=100), nullable=False),
    sa.Column('model_used', sa.String(length=100), nullable=False),
    sa.Column('token_usage', sa.Integer(), nullable=True),
    sa.Column('processing_time_seconds', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_digests_digest_type'), 'digests', ['digest_type'], unique=False)
    op.create_index(op.f('ix_digests_period_end'), 'digests', ['period_end'], unique=False)
    op.create_index(op.f('ix_digests_period_start'), 'digests', ['period_start'], unique=False)
    op.create_index(op.f('ix_digests_status'), 'digests', ['status'], unique=False)
    op.create_table('newsletters',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source', sa.Enum('GMAIL', 'SUBSTACK_RSS', 'OTHER', name='newslettersource'), nullable=False),
    sa.Column('source_id', sa.String(length=500), nullable=False),
    sa.Column('title', sa.String(length=1000), nullable=False),
    sa.Column('sender', sa.String(length=500), nullable=True),
    sa.Column('publication', sa.String(length=500), nullable=True),
    sa.Column('published_date', sa.DateTime(), nullable=False),
    sa.Column('url', sa.String(length=2000), nullable=True),
    sa.Column('raw_html', sa.Text(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('extracted_links', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='processingstatus'), nullable=False),
    sa.Column('ingested_at', sa.DateTime(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id')
    )
    op.create_index(op.f('ix_newsletters_publication'), 'newsletters', ['publication'], unique=False)
    op.create_index(op.f('ix_newsletters_published_date'), 'newsletters', ['published_date'], unique=False)
    op.create_index(op.f('ix_newsletters_source'), 'newsletters', ['source'], unique=False)
    op.create_index(op.f('ix_newsletters_status'), 'newsletters', ['status'], unique=False)
    op.create_table('newsletter_summaries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('newsletter_id', sa.Integer(), nullable=False),
    sa.Column('executive_summary', sa.Text(), nullable=False),
    sa.Column('key_themes', sa.JSON(), nullable=False),
    sa.Column('strategic_insights', sa.JSON(), nullable=False),
    sa.Column('technical_details', sa.JSON(), nullable=False),
    sa.Column('actionable_items', sa.JSON(), nullable=False),
    sa.Column('notable_quotes', sa.JSON(), nullable=False),
    sa.Column('relevance_scores', sa.JSON(), nullable=False),
    sa.Column('agent_framework', sa.String(length=100), nullable=False),
    sa.Column('model_used', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('token_usage', sa.Integer(), nullable=True),
    sa.Column('processing_time_seconds', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['newsletter_id'], ['newsletters.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('newsletter_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('newsletter_summaries')
    op.drop_index(op.f('ix_newsletters_status'), table_name='newsletters')
    op.drop_index(op.f('ix_newsletters_source'), table_name='newsletters')
    op.drop_index(op.f('ix_newsletters_published_date'), table_name='newsletters')
    op.drop_index(op.f('ix_newsletters_publication'), table_name='newsletters')
    op.drop_table('newsletters')
    op.drop_index(op.f('ix_digests_status'), table_name='digests')
    op.drop_index(op.f('ix_digests_period_start'), table_name='digests')
    op.drop_index(op.f('ix_digests_period_end'), table_name='digests')
    op.drop_index(op.f('ix_digests_digest_type'), table_name='digests')
    op.drop_table('digests')
    # ### end Alembic commands ###
