#!/usr/bin/env python3
"""Session log append utilities for OpenSpec workflow phases.

Provides functions to append structured phase entries to session-log.md
and merge-log files. Each workflow skill calls these at phase boundaries
to build a living decision record.

Functions:
  append_phase_entry  — Append a phase entry to session-log.md (creates if missing)
  append_merge_entry  — Append a merge session entry to a dated merge-log file
  count_phase_iterations — Count existing iteration entries for auto-increment
  generate_self_summary_prompt — Reference template for agent self-summary
"""

from __future__ import annotations

import re
from datetime import datetime, timezone
from pathlib import Path


SESSION_LOG_HEADER = """\
# Session Log: {change_id}

> Decision rationale, trade-offs, and alternatives recorded at each workflow phase.
> Auto-generated by workflow skills. Sanitized before commit.
"""

MERGE_LOG_HEADER = "# Merge Log: {date}\n"


def append_phase_entry(
    change_id: str,
    phase_name: str,
    content: str,
    session_log_path: str | Path | None = None,
) -> Path:
    """Append a phase entry to session-log.md.

    Creates the file with a header if it doesn't exist. Appends
    a ``---`` separator before the entry on subsequent appends.

    Args:
        change_id: OpenSpec change-id.
        phase_name: Phase name (e.g., "Plan", "Plan Iteration 2").
        content: The phase entry body (markdown, without the phase header).
        session_log_path: Override path. Defaults to
            ``openspec/changes/<change_id>/session-log.md``.

    Returns:
        The Path to the session-log.md file.
    """
    path = Path(session_log_path) if session_log_path else Path(
        f"openspec/changes/{change_id}/session-log.md"
    )
    path.parent.mkdir(parents=True, exist_ok=True)

    date_str = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    phase_header = f"## Phase: {phase_name} ({date_str})\n\n{content.rstrip()}\n"

    if path.exists():
        existing = path.read_text(encoding="utf-8")
        path.write_text(
            existing.rstrip() + f"\n\n---\n\n{phase_header}\n", encoding="utf-8"
        )
    else:
        header = SESSION_LOG_HEADER.format(change_id=change_id)
        path.write_text(header + f"\n{phase_header}\n", encoding="utf-8")

    return path


def append_merge_entry(
    date: str,
    content: str,
    merge_log_path: str | Path | None = None,
) -> Path:
    """Append a merge session entry to a dated merge-log file.

    Creates the file with a header if it doesn't exist. Appends
    a ``---`` separator before the entry on subsequent appends.

    Args:
        date: Date string (YYYY-MM-DD) for the log file name.
        content: The merge session body (markdown, without date header).
        merge_log_path: Override path. Defaults to
            ``docs/merge-logs/<date>.md``.

    Returns:
        The Path to the merge-log file.
    """
    path = Path(merge_log_path) if merge_log_path else Path(
        f"docs/merge-logs/{date}.md"
    )
    path.parent.mkdir(parents=True, exist_ok=True)

    if path.exists():
        existing = path.read_text(encoding="utf-8")
        path.write_text(
            existing.rstrip() + f"\n\n---\n\n{content.rstrip()}\n\n", encoding="utf-8"
        )
    else:
        header = MERGE_LOG_HEADER.format(date=date)
        path.write_text(header + f"\n{content.rstrip()}\n\n", encoding="utf-8")

    return path


def count_phase_iterations(
    phase_prefix: str,
    session_log_path: str | Path,
) -> int:
    """Count existing iteration entries for a phase prefix.

    Scans session-log.md for ``## Phase: <prefix>`` headers and returns
    the count. Used for auto-incrementing iteration numbers.

    Args:
        phase_prefix: The prefix to count (e.g., "Plan Iteration",
            "Implementation Iteration").
        session_log_path: Path to session-log.md.

    Returns:
        Number of existing entries matching the prefix.
    """
    path = Path(session_log_path)
    if not path.exists():
        return 0

    content = path.read_text(encoding="utf-8")
    # Match prefix followed by a digit (for "Plan Iteration 1") or "(" for date
    # This prevents "Plan" from matching "Plan Iteration" entries
    pattern = re.compile(
        rf"^## Phase: {re.escape(phase_prefix)}\s*[\d(]", re.MULTILINE
    )
    return len(pattern.findall(content))


def generate_self_summary_prompt(change_id: str) -> str:
    """Generate a structured prompt for agent self-summary.

    A reference template that agents may use to structure their phase
    entries. Not required — agents can write entries directly.
    """
    return f"""# Session Log Self-Summary Request

Please generate a session log for OpenSpec change `{change_id}` by summarizing
the current conversation. Use the following structure:

## Summary
Write 2-3 sentences summarizing what was discussed and decided.

## Key Decisions
List each significant decision with a brief rationale. Number them.

## Alternatives Considered
For each key decision, list alternatives that were discussed and why
they were rejected. Use a table format (Alternative | Why Rejected).

## Trade-offs
List explicit trade-offs accepted (e.g., "Chose X over Y because...").

## Open Questions
List any unresolved questions as checklist items.

## Session Metadata
Fill in the metadata table with:
- Agent Type: (your agent type)
- Session ID(s): (current session ID if available)
- Date Range: {datetime.now(timezone.utc).strftime('%Y-%m-%d')}
- Interactions: (approximate count)
- Source: self-summary

IMPORTANT:
- Do NOT include raw code blocks or full file contents
- Do NOT include any secrets, API keys, tokens, or passwords
- Focus on the reasoning behind decisions, not mechanical steps
- Keep the total under 500 lines
"""
