"""Shared generate/check engine for marker-managed generated inventory files.

Both the ``documentation.inventory`` and ``api.contracts`` producers render a
deterministic body into a marker-managed target file. This module owns that one
behavior so drift/creation/fail-closed semantics are identical between them:

* ``generate`` creates a missing target from a skeleton or replaces the managed
  block, writing only when bytes change;
* ``check`` renders in memory and byte-compares, never touching the checkout;
* an unbalanced/missing marker pair fails closed without writing.

Producers translate the returned :class:`BlockOutcome` list into an ri-06
:class:`ProducerResult`; this module deliberately does not build results itself,
so producer identity/version and remediation wording stay owned by each adapter.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

import markers
from _runtime import (
    ChangeKind,
    RepositoryArtifact,
    SafeError,
    ValidationResult,
    ensure_repository_relative,
    sha256_hex,
)
from results import failed_validation, passed

_FILE_HEADER = (
    "<!-- This file is generated by a project-context producer. Edit prose "
    "outside the generated markers only; content inside the markers is "
    "overwritten on regeneration. -->"
)


@dataclass(frozen=True, slots=True)
class BlockOutcome:
    """Result of applying one generated block in one mode.

    ``artifact`` is set when a path was written (generate) or would change
    (check). ``marker_error`` is set (and everything else empty) when the target
    has malformed markers, signalling the producer to fail closed.
    """

    validation: ValidationResult
    artifact: RepositoryArtifact | None = None
    drifted: bool = False
    marker_error: SafeError | None = None


def _skeleton(title: str, block_id: str, body: str) -> str:
    return (
        f"# {title}\n\n"
        f"{_FILE_HEADER}\n\n"
        f"<!-- GENERATED: begin {block_id} -->\n"
        f"{body}\n"
        f"<!-- GENERATED: end {block_id} -->\n"
    )


def apply_block(
    repository: Path,
    *,
    target_rel: str,
    block_id: str,
    title: str,
    body: str,
    mode: str,
) -> BlockOutcome:
    """Generate or check one managed block, returning a mode-neutral outcome."""
    rel = ensure_repository_relative(target_rel)
    target = repository / target_rel

    if not target.exists():
        new_text = _skeleton(title, block_id, body)
        digest = sha256_hex(new_text.encode("utf-8"))
        if mode == "generate":
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(new_text, encoding="utf-8")
            return BlockOutcome(
                validation=passed(block_id, f"created {rel}"),
                artifact=RepositoryArtifact(rel, ChangeKind.ADDED, digest),
            )
        return BlockOutcome(
            validation=failed_validation(block_id, f"{rel} is missing"),
            artifact=RepositoryArtifact(rel, ChangeKind.ADDED, digest),
            drifted=True,
        )

    current = target.read_text(encoding="utf-8")
    try:
        rendered = markers.render(current, {block_id: body})
    except markers.MarkerError as exc:
        return BlockOutcome(
            validation=failed_validation(block_id, f"marker defect in {rel}"),
            marker_error=SafeError("MarkerError", str(exc)),
        )

    if rendered == current:
        return BlockOutcome(validation=passed(block_id, f"{rel} is current"))

    digest = sha256_hex(rendered.encode("utf-8"))
    if mode == "generate":
        target.write_text(rendered, encoding="utf-8")
        return BlockOutcome(
            validation=passed(block_id, f"regenerated {rel}"),
            artifact=RepositoryArtifact(rel, ChangeKind.MODIFIED, digest),
        )
    return BlockOutcome(
        validation=failed_validation(block_id, f"{rel} is stale"),
        artifact=RepositoryArtifact(rel, ChangeKind.MODIFIED, digest),
        drifted=True,
    )
