"""``documentation.inventory`` producer — absorbed doc-sync engine (D5).

This producer owns deterministic documentation *inventories* rendered from
filesystem state into generated marker regions. It absorbs the marker engine,
filesystem-derived inventory, and prose-preservation behavior of the superseded
``add-update-documentation-skill`` while dropping that proposal's hook, cleanup,
post-merge, and auto-commit wiring (ri-10 owns gates; ri-11 owns convergence).

Freshness is content-based, never mtime-based: ``check`` renders the inventory
from the current filesystem and byte-compares it to the committed managed block.
Generated bytes depend only on the inventory inputs and the producer version —
never wall-clock time or the volatile commit SHA — so a repeat generation for
the same inputs is byte-identical (spec ``repeat-generation``) and committing the
artifact does not make it instantly stale (ri-04 provenance precedent).
"""

from __future__ import annotations

from collections.abc import Sequence
from dataclasses import dataclass
from pathlib import Path

import yaml

import results as R
from _runtime import Remediation
from inventory_file import apply_block
from registry import DOCUMENTATION_INVENTORY, Mode, Producer, ProducerSpec

PRODUCER_ID = DOCUMENTATION_INVENTORY
#: Bump when the rendered inventory format changes (invalidates freshness).
PRODUCER_VERSION = "1.0.0"
OWNER = "skills/project-context-refresh (absorbs add-update-documentation-skill)"

_REGEN_COMMAND = "make context-refresh"


@dataclass(frozen=True, slots=True)
class DocBlock:
    """One managed generated block: a target file, a block id, and a renderer."""

    target: str
    block_id: str
    renderer: str
    title: str


def _skill_frontmatter(skill_md: Path) -> dict[str, object]:
    """Parse the leading ``---`` YAML frontmatter of a SKILL.md, tolerating gaps.

    A malformed or missing frontmatter yields an empty mapping rather than
    raising, so one bad skill does not abort the whole inventory (design risk
    "Frontmatter parse errors"). The caller still records the skill by folder.
    """
    text = skill_md.read_text(encoding="utf-8")
    if not text.startswith("---"):
        return {}
    end = text.find("\n---", 3)
    if end == -1:
        return {}
    block = text[3:end]
    try:
        data = yaml.safe_load(block)
    except yaml.YAMLError:
        return {}
    return data if isinstance(data, dict) else {}


def _one_line(value: object) -> str:
    """Collapse *value* to a single trimmed line for a table cell."""
    text = "" if value is None else str(value)
    return " ".join(text.split())


def render_skills_inventory(repository: Path) -> str:
    """Render a deterministic Markdown table of every ``skills/*/SKILL.md``.

    Rows are sorted by skill folder name; the folder is the stable identity even
    when frontmatter is absent. Output is a pure function of the SKILL.md set and
    this producer version.
    """
    skills_root = repository / "skills"
    rows: list[tuple[str, str, str]] = []
    if skills_root.is_dir():
        for skill_dir in sorted(p for p in skills_root.iterdir() if p.is_dir()):
            skill_md = skill_dir / "SKILL.md"
            if not skill_md.is_file():
                continue
            meta = _skill_frontmatter(skill_md)
            name = _one_line(meta.get("name") or skill_dir.name)
            invocable = "yes" if meta.get("user_invocable") is True else "no"
            description = _one_line(meta.get("description"))
            rows.append((name, invocable, description))
    lines = [
        f"_{len(rows)} skills. Generated by {PRODUCER_ID}@{PRODUCER_VERSION}._",
        "",
        "| Skill | User-invocable | Description |",
        "| --- | --- | --- |",
    ]
    for name, invocable, description in rows:
        cell = description.replace("|", r"\|")
        lines.append(f"| `{name}` | {invocable} | {cell} |")
    return "\n".join(lines)


RENDERERS = {
    "skills_inventory": render_skills_inventory,
}

DEFAULT_BLOCKS: tuple[DocBlock, ...] = (
    DocBlock(
        target="docs/architecture-analysis/skills-inventory.md",
        block_id="skills-inventory",
        renderer="skills_inventory",
        title="Skills inventory",
    ),
)


class DocumentationInventoryProducer(Producer):
    """Adapter rendering configured documentation inventories to marker blocks."""

    def __init__(self, blocks: Sequence[DocBlock] = DEFAULT_BLOCKS) -> None:
        self._blocks = tuple(blocks)
        self.spec = ProducerSpec(
            producer_id=PRODUCER_ID,
            producer_version=PRODUCER_VERSION,
            owner=OWNER,
            inputs=("skills/*/SKILL.md",),
            outputs=tuple(sorted(block.target for block in self._blocks)),
        )

    def run(self, mode: Mode, repository: Path, source_revision: str):
        artifacts: list = []
        validations: list = []
        remediation: list[Remediation] = []
        drifted = False
        for block in self._blocks:
            body = RENDERERS[block.renderer](repository)
            outcome = apply_block(
                repository,
                target_rel=block.target,
                block_id=block.block_id,
                title=block.title,
                body=body,
                mode=mode,
            )
            if outcome.marker_error is not None:
                # Fail closed: unbalanced/missing markers never overwrite prose.
                return R.failed(
                    PRODUCER_ID,
                    PRODUCER_VERSION,
                    error=outcome.marker_error,
                    remediation=[
                        Remediation(
                            summary=(
                                f"Repair the generated markers in {block.target} "
                                f"(block {block.block_id!r}) before regenerating."
                            )
                        )
                    ],
                    validations=[outcome.validation],
                )
            validations.append(outcome.validation)
            if outcome.artifact is not None:
                artifacts.append(outcome.artifact)
            if outcome.drifted:
                drifted = True
                remediation.append(
                    Remediation(
                        summary=f"Regenerate the {block.title} inventory.",
                        command=_REGEN_COMMAND,
                    )
                )

        artifacts_sorted = R.sort_artifacts(artifacts)
        if mode == "check" and drifted:
            return R.drift(
                PRODUCER_ID,
                PRODUCER_VERSION,
                artifacts=artifacts_sorted,
                validations=validations,
                remediation=remediation,
            )
        if mode == "generate" and artifacts_sorted:
            return R.generated(
                PRODUCER_ID, PRODUCER_VERSION, artifacts=artifacts_sorted, validations=validations
            )
        return R.fresh(PRODUCER_ID, PRODUCER_VERSION, validations=validations)
