"""Outcome aggregation for /prototype-feature.

After the SKILL.md workflow has dispatched N variants, scored them via
``/validate-feature --phase smoke,spec``, and gathered the human pick-
and-choose feedback, the workflow calls into this module to:

  1. ``build_descriptor()`` — assemble a VariantDescriptor from those
     three inputs (plan + scoring + human picks).
  2. ``render_findings_markdown()`` — produce the markdown body with
     one section per variant plus an embedded JSON block per descriptor
     so /iterate-on-plan --prototype-context can parse it
     programmatically.
  3. ``write_findings_file()`` — persist the result as
     ``openspec/changes/<change-id>/prototype-findings.md``.

Spec scenarios:
  - PrototypeFindingsArtifact.findings-artifact-produced
  - PrototypeFindingsArtifact.human-pick-and-choose
  - VariantScoring.skeleton-fails-to-deploy (scoring failures are data,
    not exceptions)

Design decisions: D6 (existing validation phases for scoring),
D7 (pick-and-choose, not pick-one-winner), D9 (VariantDescriptor schema).
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from variant_descriptor import AutomatedScores, VariantDescriptor

FINDINGS_FILENAME = "prototype-findings.md"


def build_descriptor(
    *,
    variant_id: str,
    angle: str,
    vendor: str,
    change_id: str,
    scoring: dict[str, Any],
    human_picks: dict[str, bool],
    vendor_fallback: bool = False,
    synthesis_hint: str | None = None,
) -> VariantDescriptor:
    """Build a VariantDescriptor from a variant's plan + scoring + picks.

    The branch is derived deterministically from ``change_id`` and
    ``variant_id`` — the SKILL workflow guarantees they match what
    ``worktree.py setup --branch-prefix prototype --agent-id v<n>``
    produced (see wp-worktree).
    """
    return VariantDescriptor(
        variant_id=variant_id,
        angle=angle,
        vendor=vendor,
        branch=f"prototype/{change_id}/{variant_id}",
        automated_scores=AutomatedScores.from_dict(scoring),
        human_picks=dict(human_picks),
        vendor_fallback=vendor_fallback,
        synthesis_hint=synthesis_hint,
    )


def _render_variant_section(d: VariantDescriptor) -> str:
    """One ``## Variant <id>`` block.

    Embeds the structured payload as a fenced JSON block so
    /iterate-on-plan --prototype-context can ``json.loads`` it without
    fragile markdown parsing.
    """
    smoke_status = "✓ pass" if d.automated_scores.smoke_pass else "✗ fail"
    picked = sorted(k for k, v in d.human_picks.items() if v)
    picked_text = ", ".join(picked) if picked else "(none)"

    payload = json.dumps(d.to_dict(), indent=2)

    lines = [
        f"## Variant {d.variant_id}",
        "",
        f"- **Angle**: {d.angle}",
        f"- **Vendor**: {d.vendor}"
        + (" (fallback)" if d.vendor_fallback else ""),
        f"- **Branch**: `{d.branch}`",
        f"- **Smoke**: {smoke_status}",
        f"- **Spec coverage**: "
        f"{d.automated_scores.spec_covered}/{d.automated_scores.spec_total}",
        f"- **Human picks**: {picked_text}",
    ]
    if d.synthesis_hint:
        lines.append(f"- **Hint**: {d.synthesis_hint}")
    lines.extend(["", "```json", payload, "```", ""])
    return "\n".join(lines)


def render_findings_markdown(
    *,
    change_id: str,
    descriptors: list[VariantDescriptor],
) -> str:
    """Render the full prototype-findings.md body."""
    head = [
        f"# Prototype Findings — {change_id}",
        "",
        "Generated by `/prototype-feature`. Each variant section embeds a",
        "JSON block conforming to ``contracts/schemas/variant-descriptor.schema.json``",
        "for machine consumption by `/iterate-on-plan --prototype-context`.",
        "",
    ]
    sections = [_render_variant_section(d) for d in descriptors]
    return "\n".join(head + sections)


def write_findings_file(
    *,
    change_dir: Path,
    descriptors: list[VariantDescriptor],
) -> Path:
    """Persist the rendered findings to ``<change_dir>/prototype-findings.md``."""
    if not descriptors:
        raise ValueError("Cannot write findings file from empty descriptor list")
    change_dir.mkdir(parents=True, exist_ok=True)
    body = render_findings_markdown(
        change_id=change_dir.name, descriptors=descriptors
    )
    out = change_dir / FINDINGS_FILENAME
    out.write_text(body)
    return out


__all__ = [
    "FINDINGS_FILENAME",
    "build_descriptor",
    "render_findings_markdown",
    "write_findings_file",
]
