#!/usr/bin/env python3
"""Deploy phase runner — start a test environment and write .test-env.

Usage:
    python3 phase_deploy.py --env docker|neon [--seed-strategy dump_restore|migrations] \
        [--timeout 120] [--compose-file PATH] [--test-env PATH]

Design decisions:
- D2: .test-env dotenv file as handoff between deploy and smoke phases
- D3a: API runs on host via uvicorn subprocess, not inside Docker
- LST.7: On failure, exit 1 with JSON error to stderr
"""

from __future__ import annotations

import argparse
import json
import logging
import sys
from datetime import datetime, timezone
from pathlib import Path

logger = logging.getLogger(__name__)

# Ensure the scripts directory is on sys.path for imports
_SCRIPTS_DIR = Path(__file__).resolve().parent
if str(_SCRIPTS_DIR) not in sys.path:
    sys.path.insert(0, str(_SCRIPTS_DIR))

from environments.docker_stack import DockerStackEnvironment
from environments.neon_branch import NeonBranchEnvironment


def create_environment(
    env_type: str,
    seed_strategy: str = "migrations",
    compose_file: str | None = None,
) -> object:
    """Create the appropriate TestEnvironment based on env_type.

    Args:
        env_type: "docker" or "neon"
        seed_strategy: "dump_restore" or "migrations"
        compose_file: Path to docker-compose.yml (docker only)

    Returns:
        A TestEnvironment instance (DockerStackEnvironment or NeonBranchEnvironment)

    Raises:
        ValueError: If env_type is not "docker" or "neon"
    """
    if env_type == "docker":
        return DockerStackEnvironment(
            compose_file=compose_file or _find_default_compose_file(),
        )
    elif env_type == "neon":
        return NeonBranchEnvironment(seed_strategy=seed_strategy)
    else:
        raise ValueError(f"Unsupported environment type: {env_type}")


def write_test_env_file(
    path: str,
    env_vars: dict[str, str],
    env_type: str,
    seed_strategy: str,
) -> None:
    """Write a .test-env file with environment variables.

    Adds the required contract fields (TEST_ENV_TYPE, SEED_STRATEGY, STARTED_AT)
    on top of whatever env_vars the environment provides.

    Args:
        path: Output file path
        env_vars: Environment variables from TestEnvironment.env_vars()
        env_type: "docker" or "neon"
        seed_strategy: "dump_restore" or "migrations"
    """
    # Merge required contract fields with environment-provided vars
    all_vars = dict(env_vars)
    all_vars["TEST_ENV_TYPE"] = env_type
    all_vars["SEED_STRATEGY"] = seed_strategy
    all_vars["STARTED_AT"] = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")

    lines = ["# .test-env — generated by phase_deploy.py"]
    for key, value in sorted(all_vars.items()):
        # Escape values with special characters
        if any(c in value for c in (" ", '"', "'", "#", "\n")):
            escaped = value.replace("\\", "\\\\").replace('"', '\\"')
            lines.append(f'{key}="{escaped}"')
        else:
            lines.append(f"{key}={value}")
    lines.append("")  # trailing newline

    Path(path).write_text("\n".join(lines))
    logger.info("Wrote .test-env to %s", path)


def _find_default_compose_file() -> str:
    """Find the default docker-compose.yml relative to git root."""
    scripts_dir = Path(__file__).resolve().parent
    for parent in [scripts_dir] + list(scripts_dir.parents):
        compose = parent / "agent-coordinator" / "docker-compose.yml"
        if compose.exists():
            return str(compose)
    return "agent-coordinator/docker-compose.yml"


def build_parser() -> argparse.ArgumentParser:
    """Build the CLI argument parser."""
    parser = argparse.ArgumentParser(
        prog="phase_deploy",
        description="Deploy phase: start test environment and write .test-env",
    )
    parser.add_argument(
        "--env",
        choices=["docker", "neon"],
        default="docker",
        help="Environment type (default: docker)",
    )
    parser.add_argument(
        "--seed-strategy",
        choices=["dump_restore", "migrations"],
        default="migrations",
        help="Database seeding strategy (default: migrations)",
    )
    parser.add_argument(
        "--timeout",
        type=int,
        default=120,
        help="Readiness timeout in seconds (default: 120)",
    )
    parser.add_argument(
        "--compose-file",
        default=None,
        help="Path to docker-compose.yml (docker only)",
    )
    parser.add_argument(
        "--test-env",
        default=".test-env",
        help="Path to .test-env output file (default: .test-env)",
    )
    return parser


def main() -> None:
    """CLI entry point for phase_deploy."""
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s %(levelname)s %(name)s: %(message)s",
    )

    parser = build_parser()
    args = parser.parse_args()

    try:
        env = create_environment(
            env_type=args.env,
            seed_strategy=args.seed_strategy,
            compose_file=args.compose_file,
        )

        env.start()  # type: ignore[union-attr]
        env.wait_ready(timeout_seconds=args.timeout)  # type: ignore[union-attr]

        env_vars = env.env_vars()  # type: ignore[union-attr]
        write_test_env_file(
            path=args.test_env,
            env_vars=env_vars,
            env_type=args.env,
            seed_strategy=args.seed_strategy,
        )

        logger.info("Deploy phase complete. .test-env written to %s", args.test_env)

    except (RuntimeError, TimeoutError, OSError) as exc:
        error_payload = {
            "error": str(exc),
            "env": args.env,
            "phase": "deploy",
        }
        print(json.dumps(error_payload), file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
