#!/usr/bin/env python3
"""Stack launcher CLI for managing test environments.

Subcommands:
    start    — Create and start a test environment, write .test-env
    teardown — Read .test-env and tear down the environment
    status   — Read .test-env and check environment health

Design decision D2: .test-env dotenv file as phase handoff between
deploy and smoke phases.
"""

from __future__ import annotations

import argparse
import json
import logging
import subprocess
import sys
from pathlib import Path

logger = logging.getLogger(__name__)

# Ensure the scripts directory is on sys.path for imports
_SCRIPTS_DIR = Path(__file__).resolve().parent
if str(_SCRIPTS_DIR) not in sys.path:
    sys.path.insert(0, str(_SCRIPTS_DIR))

from environments.docker_stack import DockerStackEnvironment


# ---------------------------------------------------------------------------
# .test-env file I/O
# ---------------------------------------------------------------------------


def write_test_env(path: str, env_vars: dict[str, str]) -> None:
    """Write environment variables to a .test-env file in dotenv format."""
    lines = []
    lines.append("# Auto-generated by stack_launcher.py — do not edit")
    for key, value in sorted(env_vars.items()):
        # Escape values that contain special characters
        if any(c in value for c in (" ", '"', "'", "#", "\n")):
            escaped = value.replace("\\", "\\\\").replace('"', '\\"')
            lines.append(f'{key}="{escaped}"')
        else:
            lines.append(f"{key}={value}")
    lines.append("")  # trailing newline
    Path(path).write_text("\n".join(lines))
    logger.info("Wrote .test-env to %s", path)


def read_test_env(path: str) -> dict[str, str]:
    """Read a .test-env file and return a dict of key=value pairs.

    Raises FileNotFoundError if the file doesn't exist.
    """
    p = Path(path)
    if not p.exists():
        raise FileNotFoundError(f".test-env file not found: {path}")

    result: dict[str, str] = {}
    for line in p.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        if "=" not in line:
            continue
        key, _, value = line.partition("=")
        key = key.strip()
        value = value.strip()
        # Strip surrounding quotes
        if len(value) >= 2 and value[0] == value[-1] and value[0] in ('"', "'"):
            value = value[1:-1]
        result[key] = value
    return result


# ---------------------------------------------------------------------------
# Subcommands
# ---------------------------------------------------------------------------


def cmd_start(
    *,
    env_type: str,
    compose_file: str,
    test_env_path: str,
    timeout: int,
    seed_strategy: str | None,
) -> None:
    """Start a test environment and write .test-env."""
    if env_type != "docker":
        raise NotImplementedError(f"Environment type '{env_type}' not yet supported")

    env = DockerStackEnvironment(compose_file=compose_file)
    try:
        env.start()
        env.wait_ready(timeout_seconds=timeout)

        env_vars = env.env_vars()
        write_test_env(test_env_path, env_vars)

        logger.info("Test environment started successfully")
        print(json.dumps(env_vars, indent=2))
    except Exception:
        logger.error("Failed to start test environment, tearing down")
        env.teardown()
        raise


def cmd_teardown(
    *,
    test_env_path: str,
    compose_file: str,
) -> None:
    """Read .test-env and tear down the environment."""
    env_vars = read_test_env(test_env_path)
    env_type = env_vars.get("ENV_TYPE", "docker")

    if env_type != "docker":
        raise NotImplementedError(f"Environment type '{env_type}' not yet supported")

    session_id = env_vars.get("SESSION_ID")
    env = DockerStackEnvironment(compose_file=compose_file, session_id=session_id)

    # Reconstruct allocation from .test-env so teardown knows what to stop
    env._allocation = {
        "db_port": int(env_vars.get("DB_PORT", "0")),
        "api_port": int(env_vars.get("API_PORT", "0")),
        "compose_project_name": env_vars.get("COMPOSE_PROJECT_NAME", ""),
    }

    env.teardown()

    # Clean up .test-env file
    test_env = Path(test_env_path)
    if test_env.exists():
        test_env.unlink()
        logger.info("Removed .test-env file: %s", test_env_path)


def cmd_status(*, test_env_path: str) -> dict[str, object]:
    """Read .test-env and check environment health."""
    env_vars = read_test_env(test_env_path)
    db_port = env_vars.get("DB_PORT", "0")

    try:
        result = subprocess.run(
            ["pg_isready", "-h", "localhost", "-p", db_port],
            capture_output=True,
            text=True,
            timeout=5,
        )
        healthy = result.returncode == 0
    except (subprocess.TimeoutExpired, FileNotFoundError):
        healthy = False

    status = {
        "healthy": healthy,
        "env_type": env_vars.get("ENV_TYPE", "unknown"),
        "db_port": db_port,
        "session_id": env_vars.get("SESSION_ID", "unknown"),
    }
    return status


# ---------------------------------------------------------------------------
# Argument parser
# ---------------------------------------------------------------------------


def _find_default_compose_file() -> str:
    """Find the default docker-compose.yml relative to git root."""
    try:
        scripts_dir = Path(__file__).resolve().parent
        for parent in [scripts_dir] + list(scripts_dir.parents):
            compose = parent / "agent-coordinator" / "docker-compose.yml"
            if compose.exists():
                return str(compose)
    except Exception:
        pass
    return "agent-coordinator/docker-compose.yml"


def build_parser() -> argparse.ArgumentParser:
    """Build the CLI argument parser."""
    parser = argparse.ArgumentParser(
        prog="stack_launcher",
        description="Manage test environments for live service testing",
    )

    subparsers = parser.add_subparsers(dest="subcommand", required=True)

    # start
    start_parser = subparsers.add_parser("start", help="Start a test environment")
    start_parser.add_argument(
        "--env",
        choices=["docker", "neon"],
        default="docker",
        help="Environment type (default: docker)",
    )
    start_parser.add_argument(
        "--seed-strategy",
        choices=["dump_restore", "migrations"],
        default=None,
        help="Database seeding strategy",
    )
    start_parser.add_argument(
        "--timeout",
        type=int,
        default=120,
        help="Readiness timeout in seconds (default: 120)",
    )
    start_parser.add_argument(
        "--compose-file",
        default=None,
        help="Path to docker-compose.yml",
    )
    start_parser.add_argument(
        "--test-env",
        default=".test-env",
        help="Path to .test-env output file (default: .test-env)",
    )

    # teardown
    teardown_parser = subparsers.add_parser(
        "teardown", help="Tear down a test environment"
    )
    teardown_parser.add_argument(
        "--test-env",
        default=".test-env",
        help="Path to .test-env file (default: .test-env)",
    )
    teardown_parser.add_argument(
        "--compose-file",
        default=None,
        help="Path to docker-compose.yml",
    )

    # status
    status_parser = subparsers.add_parser(
        "status", help="Check test environment health"
    )
    status_parser.add_argument(
        "--test-env",
        default=".test-env",
        help="Path to .test-env file (default: .test-env)",
    )

    return parser


def main() -> None:
    """CLI entry point."""
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s %(levelname)s %(name)s: %(message)s",
    )

    parser = build_parser()
    args = parser.parse_args()

    compose_file = getattr(args, "compose_file", None) or _find_default_compose_file()

    if args.subcommand == "start":
        cmd_start(
            env_type=args.env,
            compose_file=compose_file,
            test_env_path=args.test_env,
            timeout=args.timeout,
            seed_strategy=args.seed_strategy,
        )
    elif args.subcommand == "teardown":
        cmd_teardown(
            test_env_path=args.test_env,
            compose_file=compose_file,
        )
    elif args.subcommand == "status":
        result = cmd_status(test_env_path=args.test_env)
        print(json.dumps(result, indent=2))
        if not result["healthy"]:
            sys.exit(1)


if __name__ == "__main__":
    main()
