"""Playwright TypeScript test-script generator.

Consumes :class:`TranslatedScenario` objects from :mod:`parser` plus a
frontend descriptor and emits a single ``.spec.ts`` file. The output is
designed to pass ``npx playwright test --dry-run`` (per the
"Sample frontend exercise" spec scenario), which means:

* Imports ``test`` and ``expect`` from ``@playwright/test``.
* Optionally a ``test.beforeAll`` block running the descriptor's
  ``auth_flow`` (with env-var values already resolved -- see :mod:`auth_flow`).
* One ``test('<scenario name>', ...)`` block per scenario.
* Each test body uses ``actions`` from WHEN bullets and ``assertions`` from
  THEN bullets, with selectors already expanded through the descriptor's
  ``selectors`` map by :mod:`parser`.

The generator also exposes :func:`emit_playwright_config` for the runner so
the test directory has a minimal ``playwright.config.ts`` that picks up the
descriptor's ``base_url`` and ``viewport`` defaults.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Iterable, Mapping

from auth_flow import resolve_value
from parser import PlaywrightAction, PlaywrightAssertion, TranslatedScenario


_PREAMBLE = """// Auto-generated by skills/playwright-validator. Do not edit by hand.
// Each test block corresponds to one OpenSpec Scenario, with the source_ref
// preserved as a comment so behavioral findings can trace back to the spec.
import { test, expect } from '@playwright/test';
"""


def _ts_str(value: str) -> str:
    return json.dumps(value)


def _emit_auth_flow(
    auth_flow: Iterable[Mapping[str, Any]],
    env: Mapping[str, str] | None = None,
) -> str:
    """Render the descriptor's auth_flow as a Playwright beforeAll block.

    Env-var references in ``value`` are substituted via :func:`resolve_value`
    BEFORE the script is emitted -- the resolved literal goes into the
    TypeScript source (the runner has already validated all required vars are
    present, so this MUST NOT see a missing var here).
    """
    lines: list[str] = []
    steps = list(auth_flow or [])
    if not steps:
        return ""

    lines.append("test.beforeAll(async ({ browser }) => {")
    lines.append("  const context = await browser.newContext();")
    lines.append("  const page = await context.newPage();")
    for step in steps:
        action = step.get("action")
        selector = step.get("selector")
        url = step.get("url")
        value = step.get("value")
        if isinstance(value, str):
            value = resolve_value(value, env)
        if action == "goto" and url:
            lines.append(f"  await page.goto({_ts_str(url)});")
        elif action == "fill" and selector is not None:
            lines.append(
                f"  await page.fill({_ts_str(selector)},"
                f" {_ts_str(value or '')});"
            )
        elif action == "click" and selector is not None:
            lines.append(f"  await page.click({_ts_str(selector)});")
        elif action == "wait_for_selector" and selector is not None:
            lines.append(
                f"  await page.waitForSelector({_ts_str(selector)});"
            )
        elif action == "wait_for_navigation":
            lines.append("  await page.waitForLoadState('networkidle');")
    lines.append("  await context.close();")
    lines.append("});")
    lines.append("")
    return "\n".join(lines)


def _emit_test_block(scenario: TranslatedScenario) -> str:
    """Emit a single ``test()`` block for one TranslatedScenario."""
    lines: list[str] = []
    if scenario.source_ref:
        lines.append(f"// source: {scenario.source_ref}")
    lines.append(f"test({_ts_str(scenario.test_name)}, async ({{ page }}) => {{")
    for action in scenario.actions:
        lines.append(action.to_typescript())
    for assertion in scenario.assertions:
        lines.append(assertion.to_typescript())
    lines.append("});")
    return "\n".join(lines)


def emit_test_script(
    scenarios: list[TranslatedScenario],
    descriptor: Mapping[str, Any],
    output_path: Path,
    env: Mapping[str, str] | None = None,
) -> Path:
    """Write a Playwright ``.spec.ts`` file with one test() per scenario.

    Args:
        scenarios: Translated scenarios from :func:`parser.translate_openspec_scenario`.
        descriptor: The frontend descriptor (already normalized).
        output_path: Where to write the .spec.ts file. Parent directories
            are created.
        env: Optional env mapping for auth_flow value substitution. Defaults
            to ``os.environ`` via :func:`auth_flow.resolve_value`.

    Returns:
        The path written.
    """
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    parts: list[str] = [_PREAMBLE]

    auth_flow = descriptor.get("auth_flow") or []
    auth_block = _emit_auth_flow(auth_flow, env=env)
    if auth_block:
        parts.append(auth_block)

    if not scenarios:
        # Emit a single placeholder test so playwright test --dry-run still
        # produces a parseable result. The placeholder is marked .skip so it
        # does not affect the failure count.
        parts.append(
            "test.skip('no OpenSpec scenarios were generated', async () => {});\n"
        )
    else:
        for scenario in scenarios:
            parts.append(_emit_test_block(scenario))
            parts.append("")

    output_path.write_text("\n".join(parts), encoding="utf-8")
    return output_path


def emit_playwright_config(
    descriptor: Mapping[str, Any],
    output_dir: Path,
    *,
    base_url: str | None = None,
) -> Path:
    """Write a minimal ``playwright.config.ts`` at ``output_dir``.

    The runner uses this to point the test directory at the right base URL
    and viewport. The browser matrix is passed on the CLI (``--browser=...``)
    rather than projects[] so per-browser exit codes can be aggregated by
    the runner.
    """
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    config_path = output_dir / "playwright.config.ts"
    base = base_url or descriptor.get("base_url") or "http://127.0.0.1:8000"
    viewport = descriptor.get("viewport") or {"width": 1280, "height": 720}

    body = (
        "import { defineConfig } from '@playwright/test';\n\n"
        "export default defineConfig({\n"
        "  testDir: '.',\n"
        "  reporter: 'json',\n"
        "  use: {\n"
        f"    baseURL: {_ts_str(base)},\n"
        f"    viewport: {{ width: {int(viewport['width'])},"
        f" height: {int(viewport['height'])} }},\n"
        "  },\n"
        "});\n"
    )
    config_path.write_text(body, encoding="utf-8")
    return config_path


__all__ = [
    "emit_playwright_config",
    "emit_test_script",
]
