import type { ThemeData } from "@/types/theme"

export const mockThemes: ThemeData[] = [
  {
    name: "RAG Architecture",
    description: "Retrieval-Augmented Generation patterns and best practices",
    category: "ml_ai",
    mention_count: 5,
    content_ids: [1, 2, 3],
    first_seen: "2026-03-20T00:00:00Z",
    last_seen: "2026-03-25T00:00:00Z",
    trend: "growing",
    relevance_score: 0.85,
    strategic_relevance: 0.9,
    tactical_relevance: 0.8,
    novelty_score: 0.4,
    cross_functional_impact: 0.7,
    related_themes: ["LLM Fine-tuning", "Vector Databases"],
    key_points: [
      "Hybrid retrieval combining BM25 and vector search",
      "Chunk size optimization is critical for quality",
    ],
  },
  {
    name: "LLM Fine-tuning",
    description: "Techniques for adapting foundation models to specific tasks",
    category: "ml_ai",
    mention_count: 3,
    content_ids: [2, 4],
    first_seen: "2026-03-21T00:00:00Z",
    last_seen: "2026-03-24T00:00:00Z",
    trend: "emerging",
    relevance_score: 0.72,
    strategic_relevance: 0.6,
    tactical_relevance: 0.85,
    novelty_score: 0.7,
    cross_functional_impact: 0.5,
    related_themes: ["RAG Architecture"],
    key_points: ["LoRA remains the most practical approach"],
  },
  {
    name: "Edge AI Deployment",
    description: "Running models on edge devices and mobile platforms",
    category: "devops_infra",
    mention_count: 2,
    content_ids: [5],
    first_seen: "2026-03-22T00:00:00Z",
    last_seen: "2026-03-22T00:00:00Z",
    trend: "one_off",
    relevance_score: 0.45,
    strategic_relevance: 0.3,
    tactical_relevance: 0.5,
    novelty_score: 0.6,
    cross_functional_impact: 0.3,
    related_themes: [],
    key_points: ["Nvidia Nemotron-3 Nano optimized for edge inference"],
    historical_context: {
      theme_name: "Edge AI Deployment",
      first_mention: "2025-11-01T00:00:00Z",
      total_mentions: 4,
      mention_frequency: "occasional",
      evolution_summary: "Growing interest since Nvidia and Qualcomm pushed edge inference SDKs",
      previous_discussions: ["Edge inference benchmarks from Q4 2025"],
      recent_mentions: [],
    },
  },
]

export const emptyThemes: ThemeData[] = []
