"""Agent insight model for generated findings.

Stores insights generated by the synthesis specialist or conductor,
including trends, connections, anomalies, predictions, and summaries.
"""

from datetime import UTC, datetime
from enum import StrEnum

from sqlalchemy import Column, DateTime, Float, ForeignKey, Index, String, Text, text
from sqlalchemy.dialects.postgresql import JSONB, UUID as PGUUID
from sqlalchemy.orm import relationship

from src.models.base import Base


class InsightType(StrEnum):
    """Types of insights the agent can generate."""

    TREND = "trend"
    CONNECTION = "connection"
    ANOMALY = "anomaly"
    PREDICTION = "prediction"
    SUMMARY = "summary"


class AgentInsight(Base):
    """A generated insight from agentic analysis."""

    __tablename__ = "agent_insights"

    id = Column(PGUUID(as_uuid=True), primary_key=True, server_default=text("gen_random_uuid()"))
    task_id = Column(PGUUID(as_uuid=True), ForeignKey("agent_tasks.id"), nullable=True)
    insight_type = Column(String, nullable=False)
    title = Column(String, nullable=False)
    content = Column(Text, nullable=False)
    confidence = Column(Float, nullable=False)
    tags = Column(JSONB, default=list)
    related_content_ids = Column(JSONB, default=list)
    related_theme_ids = Column(JSONB, default=list)
    metadata_ = Column("metadata", JSONB, default=dict)
    created_at = Column(DateTime, default=lambda: datetime.now(UTC))

    # Relationships
    task = relationship("AgentTask", back_populates="insights")

    __table_args__ = (
        Index("ix_agent_insights_type", "insight_type"),
        Index("ix_agent_insights_confidence", "confidence"),
        Index("ix_agent_insights_created_at", "created_at"),
    )
