"""Image model for storing extracted, keyframe, and AI-generated images.

This module provides an Image model that supports:
- Extracted images from HTML/PDF content
- YouTube video keyframes (slide captures from presentations)
- AI-generated images (future feature)

Images are linked to their source entity (Content, Summary, or Digest)
and support perceptual hash-based deduplication.
"""

import uuid
from datetime import datetime
from enum import Enum
from typing import TYPE_CHECKING

from pydantic import BaseModel, ConfigDict, Field
from sqlalchemy import (
    JSON,
    Column,
    DateTime,
    Enum as SQLEnum,
    Float,
    ForeignKey,
    Index,
    Integer,
    String,
    Text,
)
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, relationship

from src.models.base import Base

if TYPE_CHECKING:
    from src.models.content import Content
    from src.models.digest import Digest
    from src.models.summary import Summary


class ImageSource(str, Enum):
    """Image source types.

    Defines how the image was obtained:
    - EXTRACTED: Extracted from HTML/PDF/document content
    - KEYFRAME: Captured from YouTube video (slide detection)
    - AI_GENERATED: Generated by AI model (future feature)
    """

    EXTRACTED = "extracted"
    KEYFRAME = "keyframe"
    AI_GENERATED = "ai_generated"


class Image(Base):  # type: ignore[valid-type, misc]
    """Image model for unified image storage.

    Supports multiple source types with polymorphic foreign keys
    to Content, Summary, or Digest entities.

    Key design decisions:
    - UUID primary key for distributed-safe IDs
    - Perceptual hash (phash) for fuzzy deduplication
    - Polymorphic source pattern (one FK populated per image)
    - Storage abstraction via storage_provider field
    """

    __tablename__ = "images"

    id = Column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
    )

    # Source type (polymorphic discriminator)
    source_type = Column(
        SQLEnum(ImageSource, values_callable=lambda x: [e.value for e in x]),
        nullable=False,
    )

    # Foreign keys to source entities (only one should be populated)
    source_content_id = Column(
        Integer,
        ForeignKey("contents.id", ondelete="CASCADE"),
        nullable=True,
        index=True,
    )
    source_summary_id = Column(
        Integer,
        ForeignKey("summaries.id", ondelete="CASCADE"),
        nullable=True,
        index=True,
    )
    source_digest_id = Column(
        Integer,
        ForeignKey("digests.id", ondelete="CASCADE"),
        nullable=True,
        index=True,
    )

    # Original source information
    source_url = Column(String(2000), nullable=True)  # Original image URL if extracted

    # YouTube-specific metadata (for keyframes)
    # Note: index defined in __table_args__ as ix_images_video_id
    video_id = Column(String(20), nullable=True)  # YouTube video ID
    timestamp_seconds = Column(Float, nullable=True)  # Timestamp in video
    deep_link_url = Column(String(500), nullable=True)  # youtu.be/xxx?t=123

    # Storage information
    storage_path = Column(String(500), nullable=False)  # Relative path in storage
    storage_provider = Column(String(50), nullable=False, default="local")  # "local", "s3"

    # Image metadata
    filename = Column(String(255), nullable=False)
    mime_type = Column(String(100), nullable=False)
    width = Column(Integer, nullable=True)
    height = Column(Integer, nullable=True)
    file_size_bytes = Column(Integer, nullable=True)

    # Descriptive metadata
    alt_text = Column(String(500), nullable=True)
    caption = Column(Text, nullable=True)
    ai_description = Column(Text, nullable=True)  # AI-generated description

    # AI generation metadata (for source_type = 'ai_generated')
    generation_prompt = Column(Text, nullable=True)
    generation_model = Column(String(100), nullable=True)
    generation_params = Column(JSON, nullable=True)

    # Perceptual hash for deduplication
    # Note: index defined in __table_args__ as ix_images_phash
    phash = Column(String(64), nullable=True)

    # Timestamp
    created_at = Column(DateTime, nullable=False, default=datetime.utcnow)

    # Relationships
    source_content: Mapped["Content | None"] = relationship(
        "Content",
        foreign_keys=[source_content_id],
        back_populates="images",
    )
    source_summary: Mapped["Summary | None"] = relationship(
        "Summary",
        foreign_keys=[source_summary_id],
        backref="images",
    )
    source_digest: Mapped["Digest | None"] = relationship(
        "Digest",
        foreign_keys=[source_digest_id],
        backref="images",
    )

    # Table arguments
    __table_args__ = (
        Index("ix_images_source_type", "source_type"),
        Index("ix_images_phash", "phash"),
        Index("ix_images_video_id", "video_id"),
    )

    def __repr__(self) -> str:
        return (
            f"<Image(id={self.id}, source_type={self.source_type.value}, "
            f"filename='{self.filename}')>"
        )

    @property
    def dimensions(self) -> str | None:
        """Return dimensions as 'WxH' string if available."""
        if self.width and self.height:
            return f"{self.width}x{self.height}"
        return None

    def get_youtube_deep_link(self) -> str | None:
        """Generate YouTube deep link with timestamp if available."""
        if self.video_id and self.timestamp_seconds is not None:
            timestamp = int(self.timestamp_seconds)
            return f"https://youtu.be/{self.video_id}?t={timestamp}"
        return None


# --- Pydantic Schemas ---


class ImageCreate(BaseModel):
    """Schema for creating new images."""

    source_type: ImageSource
    source_content_id: int | None = None
    source_summary_id: int | None = None
    source_digest_id: int | None = None

    source_url: str | None = None

    # YouTube metadata
    video_id: str | None = None
    timestamp_seconds: float | None = None
    deep_link_url: str | None = None

    # Storage
    storage_path: str
    storage_provider: str = "local"

    # Image metadata
    filename: str
    mime_type: str
    width: int | None = None
    height: int | None = None
    file_size_bytes: int | None = None

    # Descriptive metadata
    alt_text: str | None = None
    caption: str | None = None
    ai_description: str | None = None

    # AI generation (for ai_generated source_type)
    generation_prompt: str | None = None
    generation_model: str | None = None
    generation_params: dict | None = None

    # Deduplication
    phash: str | None = None


class ImageUpdate(BaseModel):
    """Schema for updating images."""

    alt_text: str | None = None
    caption: str | None = None
    ai_description: str | None = None
    storage_path: str | None = None
    storage_provider: str | None = None


class ImageResponse(BaseModel):
    """Schema for image API responses."""

    id: uuid.UUID
    source_type: ImageSource
    source_content_id: int | None = None
    source_summary_id: int | None = None
    source_digest_id: int | None = None

    source_url: str | None = None

    # YouTube metadata
    video_id: str | None = None
    timestamp_seconds: float | None = None
    deep_link_url: str | None = None

    # Storage
    storage_path: str
    storage_provider: str

    # Image metadata
    filename: str
    mime_type: str
    width: int | None = None
    height: int | None = None
    file_size_bytes: int | None = None
    dimensions: str | None = None

    # Descriptive metadata
    alt_text: str | None = None
    caption: str | None = None
    ai_description: str | None = None

    # Deduplication
    phash: str | None = None

    created_at: datetime

    model_config = ConfigDict(from_attributes=True)


class ImageListItem(BaseModel):
    """Lightweight schema for listing images."""

    id: uuid.UUID
    source_type: ImageSource
    filename: str
    mime_type: str
    dimensions: str | None = None
    created_at: datetime

    model_config = ConfigDict(from_attributes=True)


class ImageListResponse(BaseModel):
    """Paginated image list response."""

    items: list[ImageListItem]
    total: int
    page: int = Field(default=1)
    page_size: int = Field(default=20)
    has_next: bool = Field(default=False)
    has_prev: bool = Field(default=False)


class ImageMetadata(BaseModel):
    """Metadata extracted from an image file."""

    width: int | None = None
    height: int | None = None
    mime_type: str
    file_size_bytes: int
    phash: str | None = None
