"""Runtime re-exports for the generated canonical ingestion commands."""

from src.contracts.workflow_models import (
    ArxivPaperIngestCommand,
    ArxivSearchIngestCommand,
    BlogIngestCommand,
    ConfiguredSourceCommandBase,
    FilesIngestCommand,
    GmailIngestCommand,
    HuggingFacePapersIngestCommand,
    IngestCommand,
    ObsidianVaultIngestCommand,
    PerplexitySearchIngestCommand,
    PodcastIngestCommand,
    ReadwiseIngestCommand,
    RssIngestCommand,
    ScholarPaperIngestCommand,
    ScholarReferencesIngestCommand,
    ScholarSearchIngestCommand,
    StrictModel,
    SubstackIngestCommand,
    UrlIngestCommand,
    XSearchIngestCommand,
    YouTubePlaylistIngestCommand,
    YouTubeRssIngestCommand,
)

IngestCommandBase = StrictModel

COMMAND_MODELS = (
    GmailIngestCommand,
    RssIngestCommand,
    BlogIngestCommand,
    SubstackIngestCommand,
    YouTubePlaylistIngestCommand,
    YouTubeRssIngestCommand,
    PodcastIngestCommand,
    XSearchIngestCommand,
    PerplexitySearchIngestCommand,
    FilesIngestCommand,
    UrlIngestCommand,
    ScholarSearchIngestCommand,
    ScholarPaperIngestCommand,
    ScholarReferencesIngestCommand,
    ArxivSearchIngestCommand,
    ArxivPaperIngestCommand,
    HuggingFacePapersIngestCommand,
    ReadwiseIngestCommand,
    ObsidianVaultIngestCommand,
)

__all__ = [
    "ArxivPaperIngestCommand",
    "ArxivSearchIngestCommand",
    "BlogIngestCommand",
    "COMMAND_MODELS",
    "ConfiguredSourceCommandBase",
    "FilesIngestCommand",
    "GmailIngestCommand",
    "HuggingFacePapersIngestCommand",
    "IngestCommand",
    "IngestCommandBase",
    "ObsidianVaultIngestCommand",
    "PerplexitySearchIngestCommand",
    "PodcastIngestCommand",
    "ReadwiseIngestCommand",
    "RssIngestCommand",
    "ScholarPaperIngestCommand",
    "ScholarReferencesIngestCommand",
    "ScholarSearchIngestCommand",
    "SubstackIngestCommand",
    "UrlIngestCommand",
    "XSearchIngestCommand",
    "YouTubePlaylistIngestCommand",
    "YouTubeRssIngestCommand",
]
